default: &default
  adapter: postgresql
  encoding: utf-8
  pool: 5
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: awaker_development

test:
  <<: *default
  database: awaker_test